name: Build plugin

on:
  pull_request:
    branches: ["main"]
  release:
    types: ["published"]
  push:
    branches: ["main", "dev"]
    paths:
    - Dockerfile
    - build.json
    - docker-entrypoint.sh
    - config.json
    - vault.hcl.template
    - rootfs/**
    - CHANGELOG.md
    - README.md
    - rootfs/usr/bin/*

env:
  BUILD_NAME: ha-addon-vault
  BUILD_TYPE: plugin

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.info.outputs.architectures }}
      version: ${{ steps.version.outputs.version }}
      channel: ${{ steps.version.outputs.channel }}
      publish: ${{ steps.version.outputs.publish }}
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get information
      id: info
      uses: home-assistant/actions/helpers/info@master

    - name: Get version
      id: version
      uses: home-assistant/actions/helpers/version@master
      with:
        type: ${{ env.BUILD_TYPE }}

  build:
    name: Build ${{ matrix.arch }} plugin
    needs: init
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ${{ fromJson(needs.init.outputs.architectures) }}
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
   
    - name: Login to DockerHub
      if: needs.init.outputs.publish == 'true'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set build arguments
      if: needs.init.outputs.publish == 'false'
      run: echo "BUILD_ARGS=--test" >> $GITHUB_ENV

    - name: Build plugin
      uses: home-assistant/builder@2022.06.2
      with:
        args: |
          $BUILD_ARGS \
          --${{ matrix.arch }} \
          --target /data \
          --generic ${{ needs.init.outputs.version }}

  publish:
    name: publish addon
    needs: ["init", "build"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Initialize git
      if: needs.init.outputs.publish == 'true'
      uses: home-assistant/actions/helpers/git-init@master
      with:
        name: ${{ secrets.GIT_NAME }}
        email: ${{ secrets.GIT_EMAIL }}
        token: ${{ secrets.GIT_TOKEN }}
    - name: publish addon
      shell: bash
      if: needs.init.outputs.publish == 'true'
      env:
        VERSION: ${{ needs.init.outputs.version }}
      run: |
        if [[ "$GITHUB_EVENT_NAME" = "release" ]]; then
          REPO_CHANNEL="ha-addons"
        else
          REPO_CHANNEL="ha-addons-dev"
        fi
        REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")
        rm -rf ha-addons
        git clone https://github.com/tidalf/$REPO_CHANNEL ha-addons
        mkdir -p ha-addons/$REPOSITORY_NAME 2>/dev/null
        cp CHANGELOG.md README.md logo.png icon.png ha-addons/$REPOSITORY_NAME
        jq --arg version "$VERSION" '.version = $version' config.json > ha-addons/$REPOSITORY_NAME/config.json
        cd ha-addons
        git add $REPOSITORY_NAME
        git commit -m "Automatic publish ($GITHUB_EVENT_NAME) from github.com/tidalf/ha-addon-vault"
        git push origin main
        
        
