name: Lint

env:
  SHELLCHECK_OPTS: -e SC1008 -e SC2046 -s bash

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: ShellCheck
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Run linter
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          additional_files: 'run'
